apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dataplatform
  source:
    repoURL: https://clickhouse.github.io/clickhouse-kubernetes
    chart: clickhouse
    targetRevision: 0.20.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        # Override with local values from services/clickhouse/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas